version: '3.7'
services:
  # service-one:
  #   build: ./service-one
  #   container_name: service-one
  #   ports:
  #     - '8081:80'
  # service-two:
  #   build: ./service-two
  #   container_name: service-two
  #   ports:
  #     - '8082:80'
  nginx:
    build: .
    container_name: load-balance-nginx
    ports:
      - '8080:80'
    # depends_on:
    #   - service-one
    #   - service-two